version: '3'
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - NEO4J_TEST_URL=http://neo4j:7474/db/data
    command: ["go", "test", "-mod=readonly", "-race", "-tags=integration", "-v", "./..."]
  neo4j:
    image: neo4j:3.5-enterprise
    environment:
      NEO4J_AUTH: "none"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
