[[constraint]]
  name = "github.com/Financial-Times/concepts-rw-neo4j"
  version = "^1.22.2"

[[constraint]]
  source = "github.com/Financial-Times/neoism"
  name = "github.com/jmcvetta/neoism"
  version = "^2.0.0"

[prune]
  go-tests = true
  unused-packages = true
