apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-shadow
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}-shadow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}-shadow
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}-shadow
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}-shadow
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }}-shadow
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APP_PORT
          value: "{{ .Values.env.app.port }}"
        - name: CACHE_DURATION
          value: {{ .Values.env.cache.duration }}
        - name: NEO_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: neo4j.read.only.url
        ports:
        - containerPort: {{ .Values.env.app.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.env.app.port }}
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: {{ .Values.env.app.port }}
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
